version: '3'
services:
  server:
        build: server
        image: ts/server
        restart: always
        ports:
          - 14567:14567
        deploy:
          replicas: 3
          restart_policy:
            condition: on-failure
        networks:
          - my-network

  fudanse:
    build: fudanse
    image: ts/fudanse
    restart: always
    ports:
      - 80:8080
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
    networks:
      - my-network

networks:
  my-network:
    # driver: overlay
    driver: bridge





