spring:
  application:
    name: server
  data:
    mongodb:
      host: server-mongo
#      username: user
#      password: ${MONGODB_PASSWORD}
      database: ts
      port: 27017

# HTTP Server
server:
  port: 14567  # HTTP (Tomcat) port